HorizontalFlip:
  p: 0.5
RandomBrightnessContrast:
  brightness_limit: 0.12
  contrast_limit: 0.12
  p: 0.4
GaussianBlur:
  blur_limit: 3
  p: 0.15
GaussNoise:
  std_range:
    - 0.005
    - 0.03
  p: 0.2
Rotate:
  limit: 5
  p: 0.2
Affine:
  scale:
    - 0.95
    - 1.05
  translate_percent:
    - -0.03
    - 0.03
  rotate:
    - -3
    - 3
  shear:
    - -2
    - 2
  p: 0.15
